# Generated by Django 4.2.2 on 2024-07-03 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_outfit_outfitrecommendation"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualCloset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                ("item_image", models.ImageField(upload_to="closet_items/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closet_item",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
