# Generated by Django 4.2.2 on 2024-07-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_fashionitem_category_fashionitem_image_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fashionitem",
            name="image",
            field=models.ImageField(
                default="fashion_items/default_image.jpg", upload_to="fashion_items/"
            ),
        ),
    ]
