# Generated by Django 4.2.2 on 2024-07-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_fashionitem_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualcloset",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
