# Generated by Django 4.2.2 on 2024-07-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_virtualcloset_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualcloset",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
