# Generated by Django 4.2.2 on 2024-07-22 23:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_virtualcloset_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fashionitem",
            name="description",
        ),
        migrations.RemoveField(
            model_name="virtualcloset",
            name="description",
        ),
    ]
